Repository oimodeler/oimodeler, pull requests merged in 2023-02, with the labels that each got.

#26 Fix 'fastRotator' import
  examples/ExpandingSoftware/fastRotator.py
  oimodeler/oimCustomComponents/oimFastRotator.py
Labels: bugfix

#10 Update README.md and rename logo.png to oimodelerlogo.png
  README.md
  images/oimodelerlogo.png
Labels: enhancement

#29 Remove setup.py, add pyproject.toml
  pyproject.toml
  setup.py
Labels: enhancement

#30 Hotfix relative imports
  examples/AdvancedExamples/ChromaticModelFit.py
  examples/AdvancedExamples/complexModels.py
  examples/AdvancedExamples/paramInterpolators.py
  examples/AdvancedExamples/timeDependentModelFit.py
  examples/BasicExamples/FitsImageCubeModels.py
  examples/BasicExamples/basicModels.py
  examples/BasicExamples/exampleOimData.py
  examples/BasicExamples/exampleOimDataFilter.py
  examples/BasicExamples/exampleOimFitterEmcee.py
  examples/BasicExamples/exampleOimPlot.py
  examples/BasicExamples/exampleOimSimulator.py
  examples/BasicExamples/fitsImageModel.py
  examples/BasicExamples/gettingStarted.py
  examples/ExpandingSoftware/createCustomComponentFourier.py
  examples/ExpandingSoftware/createCustomComponentImageFastRotator.py
  examples/ExpandingSoftware/createCustomComponentImageSpiral.py
  examples/ExpandingSoftware/createCustomComponentRadialProfileExpRing.py
  examples/ExpandingSoftware/createCustomParamInterpolator.py
  examples/ExpandingSoftware/usingCustomComponents.py
  examples/Other/createModelChromatic.py
  examples/PerformanceTests/simulator_ComputationTime.py
  examples/PerformanceTests/simulator_ComputationTimeRatio.py
  examples/testSuite/realDataFit.py
  examples/testSuite/simpleModelsASPROdataFit.py
  oimodeler/__init__.py
  oimodeler/oimBasicFourierComponents.py
  oimodeler/oimComponent.py
  oimodeler/oimCustomComponents/__init__.py
  oimodeler/oimCustomComponents/oimBox.py
  oimodeler/oimCustomComponents/oimFastRotator.py
  oimodeler/oimCustomComponents/oimSpiral.py
  oimodeler/oimData.py
  oimodeler/oimDataFilter.py
  oimodeler/oimFTBackends.py
  oimodeler/oimFitter.py
  oimodeler/oimModel.py
  oimodeler/oimParam.py
  oimodeler/oimPlots.py
  oimodeler/oimSimulator.py
  oimodeler/oimUtils.py
Labels: enhancement, bugfix

#36 Fix imports of __init__.py and outdated example imports
  examples/ExpandingSoftware/createCustomComponentFourier.py
  examples/ExpandingSoftware/createCustomComponentRadialProfileExpRing.py
  examples/Other/createModelChromatic.py
  oimodeler/__init__.py
  oimodeler/oimDataFilter.py
Labels: bugfix

#40 New power-law interpolator
  oimodeler/oimParam.py
  pyproject.toml
Labels: enhancement, new feature

#34 Update docs of 'oimBasicFourierComponents'
  oimodeler/oimBasicFourierComponents.py
Labels: docs, enhancement
